name: BedrockPlayerTransfer
version: '${project.version}'
main: dev.projectg.bedrockplayertransfer.SpigotBedrockPlayerTransfer
api-version: 1.17
commands:
  transfer:
    description: transfer a player to another server
    permission: bedrockplayertransfer.transfer
    aliases: /transfer